from __future__ import annotations

import math
import random
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Sequence, Tuple

import numpy as np
import pandas as pd
import os


# -----------------------------------------------------------------------------
# Simplified Generative Forests for tabular data
#
# This is a practical Python implementation inspired by the NeurIPS 2024 paper
# "Generative Forests". It keeps the core ideas:
#   - a forest of trees is trained jointly
#   - each boosting iteration splits the heaviest leaf across all trees
#   - the split is chosen by minimizing a local generative objective over the
#     current forest partition (restricted to cells with positive empirical mass)
#   - synthetic rows are generated by sampling a positive-mass partition cell and
#     then sampling uniformly inside that cell
#
# Main simplifications:
#   - uses a Gini-style Bayes risk L(p)=p(1-p)
#   - samples from final positive-mass cells instead of implementing STARUPDATE
#     explicitly; this is equivalent to sampling partition cells by empirical mass
#   - uses practical candidate split generation for numerical/categorical columns
#
# Supported data types:
#   - categorical/object/bool
#   - integer
#   - float
#
# Missing values:
#   - dropped during fitting for simplicity
#
# -----------------------------------------------------------------------------


@dataclass
class FeatureInfo:
    name: str
    kind: str  # 'categorical', 'int', 'float'
    categories: Optional[List[Any]] = None
    min_value: Optional[float] = None
    max_value: Optional[float] = None


@dataclass
class Constraint:
    kind: str  # 'categorical', 'int', 'float'
    allowed: Optional[set] = None
    low: Optional[float] = None
    high: Optional[float] = None

    def copy(self) -> "Constraint":
        return Constraint(
            kind=self.kind,
            allowed=None if self.allowed is None else set(self.allowed),
            low=self.low,
            high=self.high,
        )

    def intersect_test(self, test: "SplitTest", go_left: bool) -> Optional["Constraint"]:
        out = self.copy()
        if self.kind == "categorical":
            left_set = set(test.left_values)
            right_set = set(test.all_values) - left_set
            chosen = left_set if go_left else right_set
            out.allowed = set(out.allowed) & chosen
            return out if out.allowed else None
        else:
            if go_left:
                out.low = max(out.low, test.threshold)
            else:
                out.high = min(out.high, test.threshold)
            if out.low >= out.high:
                return None
            return out

    def contains_value(self, value: Any) -> bool:
        if pd.isna(value):
            return False
        if self.kind == "categorical":
            return value in self.allowed
        return (value >= self.low) and (value < self.high)

    def uniform_mass(self, feature: FeatureInfo) -> float:
        if self.kind == "categorical":
            total = len(feature.categories)
            return len(self.allowed) / total if total > 0 else 0.0
        denom = feature.max_value - feature.min_value
        if denom <= 0:
            return 1.0
        return max(0.0, (self.high - self.low) / denom)

    def sample(self, rng: np.random.Generator, feature: FeatureInfo) -> Any:
        if self.kind == "categorical":
            vals = list(self.allowed)
            return vals[int(rng.integers(0, len(vals)))]
        if self.kind == "int":
            lo = int(math.ceil(self.low))
            hi = int(math.floor(self.high - 1e-12))
            if hi < lo:
                hi = lo
            return int(rng.integers(lo, hi + 1))
        return float(rng.uniform(self.low, self.high))


@dataclass(frozen=True)
class SplitTest:
    feature_idx: int
    feature_name: str
    kind: str  # 'categorical' or 'numeric'
    threshold: Optional[float] = None
    left_values: Optional[Tuple[Any, ...]] = None
    all_values: Optional[Tuple[Any, ...]] = None

    def go_left(self, value: Any) -> bool:
        if self.kind == "categorical":
            return value in set(self.left_values)
        return value >= self.threshold


@dataclass
class Node:
    node_id: int
    tree_id: int
    depth: int
    constraint_by_feature: Dict[int, Constraint]
    parent: Optional[int] = None
    split_test: Optional[SplitTest] = None
    left_id: Optional[int] = None
    right_id: Optional[int] = None
    empirical_count: int = 0

    @property
    def is_leaf(self) -> bool:
        return self.split_test is None


@dataclass
class PartitionCell:
    leaf_ids: Tuple[int, ...]           # one leaf id per tree
    row_idx: np.ndarray                 # training rows in that cell
    constraints: Dict[int, Constraint]  # intersection support over all trees
    u_mass: float                       # uniform mass of this support

    @property
    def count(self) -> int:
        return int(self.row_idx.size)


class GenerativeForest:
    def __init__(
        self,
        n_trees: int = 100,
        n_splits: int = 400,
        prior_real: float = 0.5,
        max_numeric_splits: int = 16,
        max_categorical_values: int = 22,
        max_candidate_tests: int = 1000,
        random_state: Optional[int] = None,
        verbose: bool = False,
    ) -> None:
        self.n_trees = n_trees
        self.n_splits = n_splits
        self.prior_real = prior_real
        self.max_numeric_splits = max_numeric_splits
        self.max_categorical_values = max_categorical_values
        self.max_candidate_tests = max_candidate_tests
        self.verbose = verbose

        self.rng = np.random.default_rng(random_state)
        self.py_rng = random.Random(random_state)

        self.feature_info: List[FeatureInfo] = []
        self.col_names: List[str] = []
        self.X: Optional[pd.DataFrame] = None
        self.X_values: Optional[np.ndarray] = None
        self.trees: List[Dict[int, Node]] = []
        self.root_constraints: Dict[int, Constraint] = {}
        self.next_node_id = 0
        self.cells: List[PartitionCell] = []
        self._fitted = False

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------
    def fit(self, X: pd.DataFrame) -> "GenerativeForest":
        X = pd.DataFrame(X).copy()
        X = X.dropna(axis=0).reset_index(drop=True)
        if len(X) == 0:
            raise ValueError("Training data is empty after dropping missing rows.")

        self.X = X
        self.col_names = list(X.columns)
        self.feature_info = self._infer_feature_info(X)
        self.X_values = X.to_numpy(dtype=object)
        self.root_constraints = self._make_root_constraints()
        self.trees = []
        self.next_node_id = 0

        # Initialize T root-only trees.
        root_ids = []
        for t in range(self.n_trees):
            root = self._new_node(tree_id=t, depth=0, constraint_by_feature=self._copy_constraints(self.root_constraints))
            root.empirical_count = len(X)
            self.trees.append({root.node_id: root})
            root_ids.append(root.node_id)

        # Initial partition: one cell containing all rows and all roots.
        self.cells = [
            PartitionCell(
                leaf_ids=tuple(root_ids),
                row_idx=np.arange(len(X), dtype=np.int32),
                constraints=self._copy_constraints(self.root_constraints),
                u_mass=1.0,
            )
        ]

        for step in range(self.n_splits):
            leaf_ref = self._choose_heaviest_leaf()
            if leaf_ref is None:
                break
            tree_id, leaf_id = leaf_ref
            best = self._best_split_for_leaf(tree_id, leaf_id)
            if best is None:
                # Mark unsplittable leaf by setting count to -1 so it is ignored later.
                self.trees[tree_id][leaf_id].empirical_count = -1
                continue
            self._apply_split(tree_id, leaf_id, best)
            if self.verbose and ((step + 1) % 25 == 0 or step == self.n_splits - 1):
                print(f"[GF] completed split {step + 1}/{self.n_splits}, cells={len(self.cells)}")

        self._fitted = True
        return self

    def sample(self, n: int) -> pd.DataFrame:
        self._check_fitted()
        if n <= 0:
            return pd.DataFrame(columns=self.col_names)

        weights = np.array([cell.count for cell in self.cells], dtype=float)
        weights = weights / weights.sum()
        chosen = self.rng.choice(len(self.cells), size=n, replace=True, p=weights)

        rows = []
        for idx in chosen:
            cell = self.cells[int(idx)]
            row = {}
            for j, info in enumerate(self.feature_info):
                row[info.name] = cell.constraints[j].sample(self.rng, info)
            rows.append(row)
        return pd.DataFrame(rows, columns=self.col_names)

    def fit_sample(self, X: pd.DataFrame, n: Optional[int] = None) -> pd.DataFrame:
        self.fit(X)
        return self.sample(len(X) if n is None else n)

    # ------------------------------------------------------------------
    # Training internals
    # ------------------------------------------------------------------
    def _infer_feature_info(self, X: pd.DataFrame) -> List[FeatureInfo]:
        out: List[FeatureInfo] = []
        for c in X.columns:
            s = X[c]
            if pd.api.types.is_bool_dtype(s) or pd.api.types.is_object_dtype(s) or pd.api.types.is_categorical_dtype(s):
                cats = list(pd.Series(s).astype(object).dropna().unique())
                out.append(FeatureInfo(name=c, kind="categorical", categories=cats))
            elif pd.api.types.is_integer_dtype(s):
                out.append(FeatureInfo(name=c, kind="int", min_value=float(s.min()), max_value=float(s.max()) + 1.0))
            else:
                lo = float(s.min())
                hi = float(s.max())
                if hi <= lo:
                    hi = lo + 1e-9
                out.append(FeatureInfo(name=c, kind="float", min_value=lo, max_value=hi))
        return out

    def _make_root_constraints(self) -> Dict[int, Constraint]:
        out = {}
        for j, info in enumerate(self.feature_info):
            if info.kind == "categorical":
                out[j] = Constraint(kind="categorical", allowed=set(info.categories))
            else:
                out[j] = Constraint(kind=info.kind, low=info.min_value, high=info.max_value)
        return out

    def _copy_constraints(self, constraints: Dict[int, Constraint]) -> Dict[int, Constraint]:
        return {k: v.copy() for k, v in constraints.items()}

    def _new_node(self, tree_id: int, depth: int, constraint_by_feature: Dict[int, Constraint], parent: Optional[int] = None) -> Node:
        node = Node(
            node_id=self.next_node_id,
            tree_id=tree_id,
            depth=depth,
            constraint_by_feature=constraint_by_feature,
            parent=parent,
        )
        self.next_node_id += 1
        return node

    def _choose_heaviest_leaf(self) -> Optional[Tuple[int, int]]:
        best = None
        best_count = -1
        for tree_id, tree in enumerate(self.trees):
            for node_id, node in tree.items():
                if node.is_leaf and node.empirical_count > best_count:
                    best = (tree_id, node_id)
                    best_count = node.empirical_count
        return best if best_count > 0 else None

    def _bayes_risk(self, p: float) -> float:
        # Gini / square-loss Bayes risk.
        return p * (1.0 - p)

    def _cell_loss(self, r_mass: float, u_mass: float) -> float:
        m_mass = self.prior_real * r_mass + (1.0 - self.prior_real) * u_mass
        if m_mass <= 0:
            return 0.0
        p = self.prior_real * r_mass / m_mass
        return m_mass * self._bayes_risk(p)

    def _best_split_for_leaf(self, tree_id: int, leaf_id: int) -> Optional[SplitTest]:
        leaf = self.trees[tree_id][leaf_id]
        affected = [cell for cell in self.cells if cell.leaf_ids[tree_id] == leaf_id]
        if not affected:
            return None

        candidates = self._candidate_splits_for_leaf(leaf, affected)
        if not candidates:
            return None

        current_loss = 0.0
        n_rows = len(self.X)
        for cell in affected:
            current_loss += self._cell_loss(cell.count / n_rows, cell.u_mass)

        best_gain = -np.inf
        best_test = None

        for test in candidates:
            new_loss = 0.0
            valid = False
            for cell in affected:
                rows = cell.row_idx
                col = self.X_values[rows, test.feature_idx]
                if test.kind == "categorical":
                    mask_left = np.array([v in set(test.left_values) for v in col], dtype=bool)
                else:
                    vals = np.asarray(col, dtype=float)
                    mask_left = vals >= test.threshold
                c_left = int(mask_left.sum())
                c_right = int((~mask_left).sum())
                if c_left == 0 or c_right == 0:
                    # No empirical split for this cell; it contributes unchanged.
                    new_loss += self._cell_loss(cell.count / n_rows, cell.u_mass)
                    continue

                left_constraint = cell.constraints[test.feature_idx].intersect_test(test, True)
                right_constraint = cell.constraints[test.feature_idx].intersect_test(test, False)
                if left_constraint is None or right_constraint is None:
                    new_loss += self._cell_loss(cell.count / n_rows, cell.u_mass)
                    continue

                valid = True
                left_u = cell.u_mass / cell.constraints[test.feature_idx].uniform_mass(self.feature_info[test.feature_idx]) * left_constraint.uniform_mass(self.feature_info[test.feature_idx])
                right_u = cell.u_mass / cell.constraints[test.feature_idx].uniform_mass(self.feature_info[test.feature_idx]) * right_constraint.uniform_mass(self.feature_info[test.feature_idx])
                new_loss += self._cell_loss(c_left / n_rows, left_u)
                new_loss += self._cell_loss(c_right / n_rows, right_u)

            gain = current_loss - new_loss
            if gain > best_gain + 1e-15:
                best_gain = gain
                best_test = test

        return best_test if best_gain > 1e-15 else None

    def _candidate_splits_for_leaf(self, leaf: Node, affected: List[PartitionCell]) -> List[SplitTest]:
        candidates: List[SplitTest] = []
        rows = np.unique(np.concatenate([c.row_idx for c in affected]))
        if rows.size <= 1:
            return []

        for j, info in enumerate(self.feature_info):
            cons = leaf.constraint_by_feature[j]
            col = self.X_values[rows, j]
            if info.kind == "categorical":
                active_values = [v for v in sorted(set(col)) if v in cons.allowed]
                if len(active_values) <= 1:
                    continue
                if len(active_values) <= self.max_categorical_values:
                    for v in active_values:
                        candidates.append(
                            SplitTest(
                                feature_idx=j,
                                feature_name=info.name,
                                kind="categorical",
                                left_values=(v,),
                                all_values=tuple(cons.allowed),
                            )
                        )
                else:
                    self.py_rng.shuffle(active_values)
                    for v in active_values[: min(len(active_values), self.max_candidate_tests)]:
                        candidates.append(
                            SplitTest(
                                feature_idx=j,
                                feature_name=info.name,
                                kind="categorical",
                                left_values=(v,),
                                all_values=tuple(cons.allowed),
                            )
                        )
            else:
                vals = np.asarray(col, dtype=float)
                vals = vals[(vals >= cons.low) & (vals < cons.high)]
                uniq = np.unique(vals)
                if uniq.size <= 1:
                    continue
                if uniq.size <= self.max_numeric_splits + 1:
                    thresholds = uniq[:-1]
                else:
                    qs = np.linspace(0.0, 1.0, self.max_numeric_splits + 2)[1:-1]
                    thresholds = np.unique(np.quantile(vals, qs))
                for thr in thresholds:
                    if cons.low < float(thr) < cons.high:
                        candidates.append(
                            SplitTest(
                                feature_idx=j,
                                feature_name=info.name,
                                kind="numeric",
                                threshold=float(thr),
                            )
                        )

        if len(candidates) > self.max_candidate_tests:
            self.py_rng.shuffle(candidates)
            candidates = candidates[: self.max_candidate_tests]
        return candidates

    def _apply_split(self, tree_id: int, leaf_id: int, test: SplitTest) -> None:
        tree = self.trees[tree_id]
        leaf = tree[leaf_id]

        left_constraints = self._copy_constraints(leaf.constraint_by_feature)
        right_constraints = self._copy_constraints(leaf.constraint_by_feature)
        left_constraints[test.feature_idx] = left_constraints[test.feature_idx].intersect_test(test, True)
        right_constraints[test.feature_idx] = right_constraints[test.feature_idx].intersect_test(test, False)
        if left_constraints[test.feature_idx] is None or right_constraints[test.feature_idx] is None:
            leaf.empirical_count = -1
            return

        left = self._new_node(tree_id=tree_id, depth=leaf.depth + 1, constraint_by_feature=left_constraints, parent=leaf_id)
        right = self._new_node(tree_id=tree_id, depth=leaf.depth + 1, constraint_by_feature=right_constraints, parent=leaf_id)
        tree[left.node_id] = left
        tree[right.node_id] = right

        leaf.split_test = test
        leaf.left_id = left.node_id
        leaf.right_id = right.node_id

        old_cells = self.cells
        new_cells: List[PartitionCell] = []
        n_rows = len(self.X)
        left_count_total = 0
        right_count_total = 0

        for cell in old_cells:
            if cell.leaf_ids[tree_id] != leaf_id:
                new_cells.append(cell)
                continue

            rows = cell.row_idx
            col = self.X_values[rows, test.feature_idx]
            if test.kind == "categorical":
                mask_left = np.array([v in set(test.left_values) for v in col], dtype=bool)
            else:
                vals = np.asarray(col, dtype=float)
                mask_left = vals >= test.threshold

            idx_left = rows[mask_left]
            idx_right = rows[~mask_left]

            old_feature_mass = cell.constraints[test.feature_idx].uniform_mass(self.feature_info[test.feature_idx])
            if old_feature_mass <= 0:
                continue

            if idx_left.size > 0:
                cdict = self._copy_constraints(cell.constraints)
                cdict[test.feature_idx] = cdict[test.feature_idx].intersect_test(test, True)
                new_leaf_ids = list(cell.leaf_ids)
                new_leaf_ids[tree_id] = left.node_id
                left_u = cell.u_mass / old_feature_mass * cdict[test.feature_idx].uniform_mass(self.feature_info[test.feature_idx])
                new_cells.append(PartitionCell(tuple(new_leaf_ids), idx_left, cdict, left_u))
                left_count_total += int(idx_left.size)

            if idx_right.size > 0:
                cdict = self._copy_constraints(cell.constraints)
                cdict[test.feature_idx] = cdict[test.feature_idx].intersect_test(test, False)
                new_leaf_ids = list(cell.leaf_ids)
                new_leaf_ids[tree_id] = right.node_id
                right_u = cell.u_mass / old_feature_mass * cdict[test.feature_idx].uniform_mass(self.feature_info[test.feature_idx])
                new_cells.append(PartitionCell(tuple(new_leaf_ids), idx_right, cdict, right_u))
                right_count_total += int(idx_right.size)

        self.cells = new_cells
        left.empirical_count = left_count_total
        right.empirical_count = right_count_total
        leaf.empirical_count = 0

    def _check_fitted(self) -> None:
        if not self._fitted:
            raise RuntimeError("GenerativeForest is not fitted yet.")


# -----------------------------------------------------------------------------
# Example usage
# -----------------------------------------------------------------------------
# if __name__ == "__main__":
#     df = pd.DataFrame(
#         {
#             "age": [23, 25, 44, 39, 22, 24, 41, 38, 45, 20],
#             "income": [35_000, 38_000, 82_000, 74_000, 30_000, 34_000, 79_000, 71_000, 88_000, 28_000],
#             "city": ["A", "A", "B", "B", "A", "A", "B", "B", "B", "A"],
#             "owns_car": [False, False, True, True, False, False, True, True, True, False],
#         }
#     )

#     gf = GenerativeForest(
#         n_trees=20,
#         n_splits=80,
#         max_numeric_splits=8,
#         random_state=0,
#         verbose=True,
#     )
#     gf.fit(df)
#     synthetic = gf.sample(20)
#     print(synthetic.head())

def generate(train_data, n_generated, output_dir):
    df = pd.read_csv(train_data)

    gf = GenerativeForest(
        n_trees=50,
        n_splits=300,
        max_numeric_splits=12,
        random_state=42,
    )

    gf.fit(df)
    synthetic = gf.sample(n_generated)
    output_dir = os.path.join('synthetic_data', f'{output_dir}')
    synthetic.to_csv(output_dir)
    

generate('data/kaggle/ibm_hr.csv', 1500, 'kaggle_GenForest.csv')



